version: "3.2"

services:
        coqui-ai-tts:
                build: .
                command: --model_name tts_models/en/ljspeech/tacotron2-DDC_ph
                entrypoint: tts-server
                volumes:
                        - "./server.py:/root/TTS/server/server.py"
                ports:
                        - "5005:5002"
